## Estimate AR coefficients using Yule-Walker:

## Confirm Example 3.6

## The function 'acf2AR' computes AR(p) coefficients given the first p
## autocorrelations.
acf2AR(acf=c(1, 1/6, -11/24))

## Imagine having data generated by this process; we can simulate some
## using 'arima.sim' as on handout 3.
X = arima.sim(n=1000, model=list(ar=c(0.25, -0.5)))

## We can use 'acf' to compute the first 5 sample autocorrelations.
acf(X, plot=F, lag=5)

## Now fit an AR(2) process
acf2AR(acf=c(1.000,  0.166, -0.423))
## Compare these fitted AR(2) parameters to the true alpha_1 = 0.25,
## alpha_2 = -0.5.

## Alternatively, R can accomplish this in one step by using the
## function 'ar'
ar(X, order=1, aic=F)
ar(X, order=2, aic=F)




## Recall the Airline Passengers data; first repeat
## detrending/deseasonalising

ap = AirPassengers
tt = 1:length(ap) # don't use "t" as it is a function in R!
tt2 = tt^2
log.ap = log(ap)
fit3 = lm(log.ap ~ tt + tt2)
trend3 = ts(fitted(fit3), start=start(ap), frequency=frequency(ap))
resid3 = ts(residuals(fit3), start=start(ap), frequency=frequency(ap))
n = length(ap)
jan = as.numeric((1:n %% 12) == 1)
feb = as.numeric((1:n %% 12) == 2)
mar = as.numeric((1:n %% 12) == 3)
apr = as.numeric((1:n %% 12) == 4)
may = as.numeric((1:n %% 12) == 5)
jun = as.numeric((1:n %% 12) == 6)
jul = as.numeric((1:n %% 12) == 7)
aug = as.numeric((1:n %% 12) == 8)
sep = as.numeric((1:n %% 12) == 9)
oct = as.numeric((1:n %% 12) == 10)
nov = as.numeric((1:n %% 12) == 11)
dec = as.numeric((1:n %% 12) == 0)
fit4 = lm(resid3 ~ 0 + jan + feb + mar + apr + may + jun + jul + aug +
  sep + aug + oct + nov + dec)
seasonal = ts(fitted(fit4), start=start(ap), end=end(ap),
  frequency=frequency(ap))
fv = trend3 + seasonal
resid5 = log.ap - fv


## Plot data, detrended, and deseasonalised along with correlograms.
par(mfrow=c(4,2), mar=c(4,4,1,1)+0.1)
plot(log.ap, ylab="Data"); acf(log.ap, main="")
plot(resid3, ylab="Detrended"); acf(resid3, main="")
plot(resid5, ylab="Deseasonalised"); acf(resid5, main="")

## Now fit AR(1) and plot residuals
acf(resid5, plot=F, lag=1) # alpha hat = rho hat 1 = 0.671

## Fit AR(1) and store results
arfit = ar(resid5, order=1, aic=F) 
arfit # Print fit summary; confirms alpha hat = 0.671

## Examine structure of the stored results of fitting AR(1).
str(arfit)
## Note residuals are computed as the 'resid' component of the object.
## This is a time series, so we can plot it and its correlogram:
plot(arfit$resid, ylab="AR residuals")
acf(arfit$resid, na.action=na.omit, main="")
## Note we have to tell R to ignore NAs since the first observation
## has no residual (it can't be predicted without initial conditions).
## The correlogram is now consistent with white noise,so no further
## modelling is required.

par(mfrow=c(1,1))
